services:
  - type: web
    name: expense-tracker
    env: node
    plan: free
    runtime: "20"

    buildCommand: cd server && npm install
    startCommand: cd server && npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: "10000"

      - key: JWT_SECRET
        generateValue: true

      - key: CORS_ORIGIN
        value: "https://expense-tracker-o0ni.onrender.com"

      - key: DATABASE_URL
        value: "postgresql://user:password@host/dbname?sslmode=require"
